# Global Hugo setting
baseURL = 'https://dragonwasrobot.com/'
languageCode = 'en-us'
title = 'dragonwasrobot'
enableRobotsTXT = true

[menus]
  # Config for setting up menus. Left intentionally empty as everything is on
  # the front page.

[markup.goldmark.renderer]
  # Hugo uses Goldmark for rendering markdown to HTML.
  # The `unsafe` flag allows embedding arbitrary raw HTML in markdown files.
  unsafe = true

[markup]
  [markup.highlight]
    # Hugo uses Chroma for syntax highlighting.
    # The `noClasses` flag disables the default themed based coloring, e.g.
    # `style = 'nord'`.
    noClasses = false

[outputs]
  # Determines the output formats for each page kind.
  home = ['html', 'rss']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[caches]
  [caches.images]
    # Specifies where to store cached images.
    dir = ':cacheDir/images'
  [caches.assets]
    dir = ':cacheDir/assets'

[build]
  [build.buildStats]
    # `buildStats` determines whether to create a hugo_stats.json containing
    # arrays of the class attributes, id attributes, and tags of every HTML
    # element.
    enable = true
  [[build.cachebusters]]
    # Sets up cache busting for css assets
    source = 'assets/watching/hugo_stats\.json'
    target = 'styles\\.css'

[module]
  [module.hugoVersion]
    # The `extended` flag determines whether to include support for SASS/SCSS.
    extended = false
    min = '0.146.0'
  [[module.mounts]]
    # Specifies mounts from project sources into Hugo virtual file system.
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'hugo_stats.json'
    target = 'assets/watching/hugo_stats.json'
