baseURL = 'https://dragonwasrobot.com/'
languageCode = 'en-us'
title = 'dragonwasrobot'

[menus]
  # empty for now, trying to fit everything in the front page and individual
  # blog posts and pages

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    # disable highlighting theme and use own CSS styling
    # to renable set: `style = 'xcode'`
    noClasses = false

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[outputs]
  home = ['html', 'rss']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[caches]
  [caches.images]
    dir = ':cacheDir/images'
